{
 "title": "Landing Dashboard - APM",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(apm_environment,environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Environments and Services",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (environment, service_name) (\r\n  avg_over_time(apm_latency{\r\n    environment=~\"$environment\"\r\n  }[$__range])\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (environment,service_name)(count_over_time(apm_transaction_event{\r\n  environment=~\"$environment\"\r\n  \r\n}[$__range]))\r\n/\r\n(\r\n  (${__range_s}) / 60 + 1\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  sum by (environment,service_name)(count_over_time(apm_transaction_status{\r\n    environment=~\"$environment\",\r\n    transaction_status=~\"5..\"\r\n  }[$__range]))\r\n  /\r\n  sum by (environment,service_name)(count_over_time(apm_transaction_status{\r\n    environment=~\"$environment\"\r\n  }[$__range]))\r\n) * 100\r\nor\r\n(\r\n  sum by (environment,service_name)(count_over_time(apm_transaction_status{\r\n    environment=~\"$environment\"\r\n  }[$__range])) * 0\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(last_over_time(apm_alert{environment=~\"$environment\",endpoint_name!=\"\",severity!=\"Info\"}[$__range]), \"start_time\", \"$1 $2\", \"start_time\", \"(.*)T(.*)Z\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(last_over_time(apm_alert{environment=~\"$environment\",endpoint_name=\"\",severity!=\"Info\"}[$__range]), \"start_time\", \"$1 $2\", \"start_time\", \"(.*)T(.*)Z\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}