{
 "title": "Service Detail Dashboard - APM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "Environment",
    "query": {
     "query": "label_values(apm_environment,environment)"
    }
   },
   {
    "name": "Application",
    "label": "Service",
    "query": {
     "query": "label_values(apm_service_name{environment=~\"$Environment\"},service_name)"
    }
   },
   {
    "name": "Transaction",
    "query": {
     "query": "label_values(apm_latency{environment=~\"$Environment\",service_name=~\"$Application\",event=\"TRANSACTION\"},transaction_name)"
    }
   },
   {
    "name": "Hostname",
    "query": {
     "query": "label_values(apm_latency{environment=~\"$Environment\",service_name=~\"$Application\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  sum by (transaction_name, method, service_name)(\n    count_over_time(apm_transaction_event{\n      environment=~\"$Environment\",\n      service_name=~\"$Application\",\n      transaction_name=~\"$Transaction\",\n      hostname=~\"$Hostname\",\n      event=\"TRANSACTION\"\n    }[$__range])\n  )\n  /\n  (\n    (${__range_s}) / 60 + 1\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "avg by(transaction_name,method,service_name) (avg_over_time(apm_latency{\r\n    environment=~\"$Environment\",\r\n    service_name=~\"$Application\",\r\n    transaction_name=~\"$Transaction\",\r\n    hostname=~\"$Hostname\",\r\n    event=\"TRANSACTION\"\r\n  }[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  sum by (transaction_name,method,service_name)(count_over_time(apm_transaction_status{\r\n    environment=~\"$Environment\",\r\n    service_name=~\"$Application\",\r\n    transaction_name=~\"$Transaction\",\r\n    hostname=~\"$Hostname\",\r\n    transaction_status=~\"5..\",event=\"TRANSACTION\"\r\n  }[$__range]))\r\n  /\r\n  sum by (transaction_name,method,service_name)(count_over_time(apm_transaction_status{\r\n    environment=~\"$Environment\",\r\n    service_name=~\"$Application\",\r\n    transaction_name=~\"$Transaction\",\r\n    hostname=~\"$Hostname\",\r\n    event=\"TRANSACTION\"\r\n  }[$__range]))\r\n) * 100\r\nor\r\n(\r\n  sum by (transaction_name,method,service_name)(count_over_time(apm_transaction_status{\r\n    environment=~\"$Environment\",\r\n    service_name=~\"$Application\",\r\n    transaction_name=~\"$Transaction\",\r\n    hostname=~\"$Hostname\",\r\n    event=\"TRANSACTION\"\r\n  }[$__range])) * 0\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (transaction_name, method,service_name)(count_over_time(apm_transaction_event{\r\n  environment=~\"$Environment\",\r\n  service_name=~\"$Application\",\r\n  transaction_name=~\"$Transaction\",\r\n  hostname=~\"$Hostname\",\r\n  event=\"TRANSACTION\"\r\n}[$__range]))\r\n/\r\n(\r\n  (${__range_s}) / 60 + 1\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed transaction rate(%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n  (\n    sum by (transaction_name, method, service_name)(count_over_time(apm_transaction_status{\n      environment=~\"$Environment\",\n      service_name=~\"$Application\",\n      transaction_name=~\"$Transaction\",\n      hostname=~\"$Hostname\",\n      transaction_status=~\"5..\",\n      event=\"TRANSACTION\"\n    }[$__range]))\n    /\n    sum by (transaction_name, method, service_name)(count_over_time(apm_transaction_status{\n      environment=~\"$Environment\",\n      service_name=~\"$Application\",\n      transaction_name=~\"$Transaction\",\n      hostname=~\"$Hostname\",\n      event=\"TRANSACTION\"\n    }[$__range]))\n  ) * 100\n)\nor\navg(\n  sum by (transaction_name, method, service_name)(count_over_time(apm_transaction_status{\n    environment=~\"$Environment\",\n    service_name=~\"$Application\",\n    transaction_name=~\"$Transaction\",\n    hostname=~\"$Hostname\",\n    event=\"TRANSACTION\"\n  }[$__range])) * 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dependencies",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (transaction_sub_type) (\n  avg_over_time(apm_latency{\n    environment=~\"$Environment\",\n    service_name=~\"$Application\",\n    hostname=~\"$Hostname\",\n    event=\"SPAN\",\n    transaction_sub_type!=\"\"\n  }[$__range])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  sum by (transaction_sub_type)(count_over_time(apm_transaction_status{\n    environment=~\"$Environment\",\n    service_name=~\"$Application\",\n    hostname=~\"$Hostname\",\n    transaction_status=~\"5..\",\n    event=\"SPAN\",\n    transaction_sub_type!=\"\"\n  }[$__range]))\n  /\n  sum by (transaction_sub_type)(count_over_time(apm_transaction_status{\n    environment=~\"$Environment\",\n    service_name=~\"$Application\",\n    hostname=~\"$Hostname\",\n    event=\"SPAN\",\n    transaction_sub_type!=\"\"\n  }[$__range]))\n) * 100\nor\n(\n  sum by (transaction_sub_type)(count_over_time(apm_transaction_status{\n    environment=~\"$Environment\",\n    service_name=~\"$Application\",\n    hostname=~\"$Hostname\",\n    event=\"SPAN\",\n    transaction_sub_type!=\"\"\n  }[$__range])) * 0\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (transaction_sub_type)(count_over_time(apm_transaction_event{\n  environment=~\"$Environment\",\n  service_name=~\"$Application\",\n  hostname=~\"$Hostname\",\n  event=\"SPAN\",\n  transaction_sub_type!=\"\"\n}[$__range]))\n/\n(\n  (${__range_s}) / 60 + 1\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status 2XX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apm_transaction_status_code_series{\n  environment=~\"$Environment\",\n  service_name=~\"$Application\",\n  transaction_name=~\"$Transaction\",\n  hostname=~\"$Hostname\",\n  status_code_series=\"HTTP 2xx\"\n}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status 3XX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apm_transaction_status_code_series{\n  environment=~\"$Environment\",\n  service_name=~\"$Application\",\n  transaction_name=~\"$Transaction\",\n  hostname=~\"$Hostname\",\n  status_code_series=\"HTTP 3xx\"\n}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status 5XX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apm_transaction_status_code_series{\n  environment=~\"$Environment\",\n  service_name=~\"$Application\",\n  transaction_name=~\"$Transaction\",\n  hostname=~\"$Hostname\",\n  status_code_series=\"HTTP 5xx\"\n}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status 4XX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apm_transaction_status_code_series{\n  environment=~\"$Environment\",\n  service_name=~\"$Application\",\n  transaction_name=~\"$Transaction\",\n  hostname=~\"$Hostname\",\n  status_code_series=\"HTTP 4xx\"\n}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "avg_over_time(apm_cpu_system_average{environment=~\"$Environment\", service_name=~\"$Application\", hostname=~\"$Hostname\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(apm_cpu_process_average{environment=~\"$Environment\", service_name=~\"$Application\", hostname=~\"$Hostname\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(apm_system_memory_usage_avg_total{environment=~\"$Environment\", service_name=~\"$Application\", hostname=~\"$Hostname\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(apm_system_memory_usage_avg{environment=~\"$Environment\", service_name=~\"$Application\", hostname=~\"$Hostname\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "label_replace(last_over_time(apm_alert{environment=~\"$Environment\",service_name=~\"$Application\",hostname=~\"$Hostname\",endpoint_name!=\"\",severity!=\"Info\"}[$__range]), \"start_time\", \"$1 $2\", \"start_time\", \"(.*)T(.*)Z\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(last_over_time(apm_alert{environment=~\"$Environment\",service_name=~\"$Application\",hostname=~\"$Hostname\",endpoint_name=\"\",severity!=\"Info\"}[$__range]), \"start_time\", \"$1 $2\", \"start_time\", \"(.*)T(.*)Z\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}