{
 "title": "Transaction Detail Dashboard - APM",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": {
     "query": "label_values(apm_service_name,service_name)"
    }
   },
   {
    "name": "Transaction",
    "query": {
     "query": "label_values(apm_latency{event=\"TRANSACTION\",service_name=~\"$Application\"},transaction_name)"
    }
   },
   {
    "name": "Hostname",
    "query": {
     "query": "label_values(apm_latency{event=\"TRANSACTION\",service_name=~\"$Application\",transaction_name=~\"$Transaction\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apm_transaction_event{\n  transaction_name=~\"$Transaction\",\n  service_name=~\"$Application\",\n  hostname=~\"$Hostname\",\n  event=\"TRANSACTION\"\n}[5m])) / 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Transaction Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(count_over_time(apm_transaction_status{\n    transaction_name=~\"$Transaction\",\n    service_name=~\"$Application\",\n    hostname=~\"$Hostname\",\n    transaction_status=~\"5..\",\n    event=\"TRANSACTION\"\n  }[$__range]))\n  /\n  sum(count_over_time(apm_transaction_status{\n    transaction_name=~\"$Transaction\",\n    service_name=~\"$Application\",\n    hostname=~\"$Hostname\",\n    event=\"TRANSACTION\"\n  }[$__range]))\n) * 100\nor\n(\n  sum(count_over_time(apm_transaction_status{\n    transaction_name=~\"$Transaction\",\n    service_name=~\"$Application\",\n    hostname=~\"$Hostname\",\n    event=\"TRANSACTION\"\n  }[$__range])) * 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status 2XX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apm_transaction_status_code_series{\n  transaction_name=~\"$Transaction\",\n  service_name=~\"$Application\",\n  hostname=~\"$Hostname\",\n  status_code_series=\"HTTP 2xx\",\n  event=\"TRANSACTION\"\n}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status 5XX",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apm_transaction_status_code_series{\n  transaction_name=~\"$Transaction\",\n  service_name=~\"$Application\",\n  hostname=~\"$Hostname\",\n  status_code_series=\"HTTP 5xx\",\n  event=\"TRANSACTION\"\n}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status 4XX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apm_transaction_status_code_series{\n  transaction_name=~\"$Transaction\",\n  service_name=~\"$Application\",\n  hostname=~\"$Hostname\",\n  status_code_series=\"HTTP 4xx\",\n  event=\"TRANSACTION\"\n}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status 3XX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(apm_transaction_status_code_series{\n  transaction_name=~\"$Transaction\",\n  service_name=~\"$Application\",\n  hostname=~\"$Hostname\",\n  status_code_series=\"HTTP 3xx\",\n  event=\"TRANSACTION\"\n}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(last_over_time(apm_latency{\n  transaction_name=~\"$Transaction\",\n  service_name=~\"$Application\",\n  hostname=~\"$Hostname\",\n  event=\"TRANSACTION\"\n}[$__range]), \"start_time\", \"$1 $2\", \"start_time\", \"(.*)T(.*)Z\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(\n  count(\n    last_over_time(\n      apm_latency{\n        service_name=~\"$Application\",\n        transaction_name=~\"$Transaction\",\n        hostname=~\"$Hostname\",\n        event=\"TRANSACTION\"\n      }[$__range]\n    ) <= 50\n  ), \"bucket\", \"≤50ms\", \"\", \"\"\n)\nor\nlabel_replace(\n  count(\n    last_over_time(\n      apm_latency{\n        service_name=~\"$Application\",\n        transaction_name=~\"$Transaction\",\n        hostname=~\"$Hostname\",\n        event=\"TRANSACTION\"\n      }[$__range]\n    ) > 50 <= 100\n  ), \"bucket\", \"50-100ms\", \"\", \"\"\n)\nor\nlabel_replace(\n  count(\n    last_over_time(\n      apm_latency{\n        service_name=~\"$Application\",\n        transaction_name=~\"$Transaction\",\n        hostname=~\"$Hostname\",\n        event=\"TRANSACTION\"\n      }[$__range]\n    ) > 100 <= 200\n  ), \"bucket\", \"100-200ms\", \"\", \"\"\n)\nor\nlabel_replace(\n  count(\n    last_over_time(\n      apm_latency{\n        service_name=~\"$Application\",\n        transaction_name=~\"$Transaction\",\n        hostname=~\"$Hostname\",\n        event=\"TRANSACTION\"\n      }[$__range]\n    ) > 200 <= 500\n  ), \"bucket\", \"200-500ms\", \"\", \"\"\n)\nor\nlabel_replace(\n  count(\n    last_over_time(\n      apm_latency{\n        service_name=~\"$Application\",\n        transaction_name=~\"$Transaction\",\n        hostname=~\"$Hostname\",\n        event=\"TRANSACTION\"\n      }[$__range]\n    ) > 500\n  ), \"bucket\", \">500ms\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "label_replace(last_over_time(apm_alert{\n  endpoint_name=~\"$Transaction\",\n  service_name=~\"$Application\",\n  hostname=~\"$Hostname\",\n  severity!=\"Info\"\n}[$__range]), \"start_time\", \"$1 $2\", \"start_time\", \"(.*)T(.*)Z\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}